### ISSUE TITLE
Brief Summary of various keras layers used

### ISSUE THREAD

**Issue by gomrinal** [ai4all-sfu/NLP_2020#2]
Hi Alice,
Can you please prepare a slide which could have brief explanation of the various keras layers used for the training?
Thank you

**Comment by atol** [comment]
Do you have the original Powerpoint file so I can just insert the new slides? Thanks!

**Comment by gomrinal** [comment]
Yes! here you go :
https://docs.google.com/presentation/d/1bbfDS8cQ5QspLrrsVWOSJxo5ShJBdUdBfGiVgukl-B8/edit?usp=sharing
